### ISSUE TITLE
QudUX Fails to Build on 2.0.203.56

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [egocarib/CavesOfQud-QudUX-v2#20]
This includes the fix in #19 which fixed a number of other issues. Unfortunately I don't know a thing about CS and cannot propose a solution to this error or the warnings.

=== QudUX 2.0 Errors ===
C:\Users\Kryik\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\1804499742\Screen Extenders\CreateCharacterExtender.cs(70,22): error CS1061: 'HologramMaterial' does not contain a definition for 'Tile' and no accessible extension method 'Tile' accepting a first argument of type 'HologramMaterial' could be found (are you missing a using directive or an assembly reference?)

== Warnings ==

C:\Users\Kryik\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\1804499742\Screen Extenders\EnhancedScoreBoard.cs(186,20): warning CS0108: 'EnhancedScoreEntry.Level' hides inherited member 'ScoreEntry2.Level'. Use the new keyword if hiding was intended.
C:\Users\Kryik\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\1804499742\Screen Extenders\EnhancedScoreBoard.cs(188,23): warning CS0108: 'EnhancedScoreEntry.Version' hides inherited member 'ScoreEntry2.Version'. Use the new keyword if hiding was intended.

**Comment by egocarib** [comment]
obsoleted by #24 - latest game version now works
