### ISSUE TITLE
QudUX fails to build on 203.45

### ISSUE THREAD

**Issue by AsheIsAmazing** [egocarib/CavesOfQud-QudUX-v2#16]
Presumably due to the modding changes to `HighScores.json`, QudUX fails to build with the following:
`[2022-06-11T16:24:57] === QUDUX ===`

`[2022-06-11T16:24:57] Compiling 61 files...`

`[2022-06-11T16:24:57] Failure :(`

`[2022-06-11T16:24:57] == COMPILER ERRORS ==`

`[2022-06-11T16:24:57] C:\Users\addic\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\QudUX\Screen Extenders\EnhancedScoreBoard.cs(51,95): error CS1061: 'ScoreEntry2' does not contain a definition for 'Description' and no accessible extension method 'Description' accepting a first argument of type 'ScoreEntry2' could be found (are you missing a using directive or an assembly reference?)`

`[2022-06-11T16:24:57] C:\Users\addic\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\QudUX\Screen Extenders\EnhancedScoreBoard.cs(51,61): error CS7036: There is no argument given that corresponds to the required formal parameter 'Name' of 'ScoreEntry2.ScoreEntry2(int, string, long, string, string, int, string)'`

`[2022-06-11T16:24:57] == COMPILER WARNINGS ==`

`[2022-06-11T16:24:57] C:\Users\addic\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\QudUX\Screen Extenders\EnhancedScoreBoard.cs(186,20): warning CS0108: 'EnhancedScoreEntry.Level' hides inherited member 'ScoreEntry2.Level'. Use the new keyword if hiding was intended.`

`[2022-06-11T16:24:57] C:\Users\addic\AppData\LocalLow\Freehold Games\CavesOfQud\Mods\QudUX\Screen Extenders\EnhancedScoreBoard.cs(188,23): warning CS0108: 'EnhancedScoreEntry.Version' hides inherited member 'ScoreEntry2.Version'. Use the new keyword if hiding was intended.`

**Comment by egocarib** [comment]
obsoleted by #24 - latest game version now works
