### ISSUE TITLE
QudUX Fails to Build on 2.0.204.49

### ISSUE THREAD

**Issue by JonasmanTheBotty** [egocarib/CavesOfQud-QudUX-v2#22]
I am running Qud on an M1 Mac with MacOS Ventura 13.1
```
=== QudUX 2.0 Errors ===
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Utilities/TileMaker.cs(137,76): error CS1061: 'Examiner' does not contain a definition for 'UnknownTile' and no accessible extension method 'UnknownTile' accepting a first argument of type 'Examiner' could be found (are you missing a using directive or an assembly reference?)
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Utilities/TileMaker.cs(139,48): error CS1061: 'Examiner' does not contain a definition for 'UnknownTile' and no accessible extension method 'UnknownTile' accepting a first argument of type 'Examiner' could be found (are you missing a using directive or an assembly reference?)
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CreateCharacterExtender.cs(70,22): error CS1061: 'HologramMaterial' does not contain a definition for 'Tile' and no accessible extension method 'Tile' accepting a first argument of type 'HologramMaterial' could be found (are you missing a using directive or an assembly reference?)
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/EnhancedScoreBoard.cs(51,95): error CS1061: 'ScoreEntry2' does not contain a definition for 'Description' and no accessible extension method 'Description' accepting a first argument of type 'ScoreEntry2' could be found (are you missing a using directive or an assembly reference?)
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/EnhancedScoreBoard.cs(51,61): error CS7036: There is no argument given that corresponds to the required formal parameter 'Name' of 'ScoreEntry2.ScoreEntry2(int, string, long, string, string, int, string)'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screens/QudUX_InventoryScreen.cs(574,64): error CS7036: There is no argument given that corresponds to the required formal parameter 'buffer' of 'ImposterManager.getImposterUpdateFrame(ScreenBuffer)'
== Warnings ==
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/EnhancedScoreBoard.cs(186,20): warning CS0108: 'EnhancedScoreEntry.Level' hides inherited member 'ScoreEntry2.Level'. Use the new keyword if hiding was intended.
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/EnhancedScoreBoard.cs(188,23): warning CS0108: 'EnhancedScoreEntry.Version' hides inherited member 'ScoreEntry2.Version'. Use the new keyword if hiding was intended.
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(183,38): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(183,89): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(205,38): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(205,89): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(206,42): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(206,93): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(207,36): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(207,85): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(239,39): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(239,83): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(246,50): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(246,101): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(254,39): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(254,88): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(257,46): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
<...>/steamapps/common/Caves of Qud/CoQ.app/Contents/Resources/Data/StreamingAssets/Mods/CavesOfQud-QudUX-v2-master/Screen Extenders/CharacterTileScreenExtender.cs(257,97): warning CS0618: 'GamePartBlueprint.Parameters.get' is obsolete: 'Parameters are now stored parsed.  Use TryGetParameter<T> to get the parsed value, or GetParameterString() to get the original string.  If you really need a full iterator for Parameters to strings, use GetParameterStrings() -- Will remove Q2 2023'
```

**Comment by egocarib** [comment]
obsoleted by #24 - latest game version now works
